### ISSUE TITLE
Why do we need to calculate the homography matrix twice?

### ISSUE THREAD

**Issue by AbyssGaze** [NeurAI-Lab/biHomE#5] opened 2021-12-28 03:43 UTC
Thank you very much for your work, but I have some questions:
1. In https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/PerceptualHead.py#L177 used DSAC to calculate homography and four points offset
2.  In https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/PerceptualHead.py#L371 used four points offsets to calculate homography and warp feature map.
Actually homography matrix was calculated twice, but the homography matrix is a little different.
Thanks!

**Comment by dkoguciuk** [comment] 2022-01-31 22:14
Hi @AbyssGaze ,

good catch! This is just for my convenience: I wanted to have a clean design regardless of the used backbone. The difference is **very, very small** and it's caused by the sole nature of floating point operations.

Best,
D

**Comment by dkoguciuk** [comment] 2022-02-13 22:06
Hi @AbyssGaze , I'm closing the issue for now. If you have any other questions feel free to reopen it.

**Closed as completed by dkoguciuk** 2022-02-13 22:06 UTC
